# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class PerformCli < Formula
  desc ""
  homepage "https://cultureamp.github.io/perform-cli/"
  version "10.11.12"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/cultureamp/perform-cli/releases/download/v10.11.12/perform-cli_10.11.12_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "3dfcf478f965518f8ffa8f824ee40e36361a7751186370784338676740e2022f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/cultureamp/perform-cli/releases/download/v10.11.12/perform-cli_10.11.12_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "536000fd17a50244f41ccbf3678e1247229fed303368a2c6834450a223cecdc3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/cultureamp/perform-cli/releases/download/v10.11.12/perform-cli_10.11.12_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "e372431a93f71241dab80d3632369e4c40e08579a39fa220d377263c63de96dd"
  end

  def install
    bin.install "perform-cli"
    bin.install "perform-cli-logs"
    bin.install "perform-cli-status"
  end
end
