# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class PerformCli < Formula
  desc ""
  homepage "https://cultureamp.github.io/perform-cli/"
  version "10.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cultureamp/perform-cli/releases/download/v10.1.3/perform-cli_10.1.3_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "0d69c0cb5c8db7a354298c1f4eedc49a5b4320301eec523f92d26c7b156ae356"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cultureamp/perform-cli/releases/download/v10.1.3/perform-cli_10.1.3_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "765e172ec2848d7c867f5b5ec815ff573221dab36061dd489b4f6a21b477a3f6"
    end
  end

  def install
    bin.install "perform-cli"
    bin.install "perform-cli-logs"
    bin.install "perform-cli-status"
  end
end
